import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { LogOutModal, UserProfile } from "../components/index";
import "../styles/main.scss";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--var-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        {children}
        <LogOutModal />
        <UserProfile />
      </body>
    </html>
  );
}
